name: example
description: flutter_html example app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.22.2 <3.24.0"

dependencies:
  flutter_html:
    path: ..
  flutter_html_all:
    path: ../packages/flutter_html_all
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg