name: flutter_html_all
description: All optional flutter_html widgets, bundled into a single package.
version: 3.0.0-alpha.5
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ^3.0.0
  flutter: ">=3.22.2 <3.24.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html:     
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
  flutter_html_audio:     
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
      path: packages/flutter_html_audio
  flutter_html_iframe: 
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
      path: packages/flutter_html_iframe
  flutter_html_math: 
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
      path: packages/flutter_html_math
  flutter_html_svg: 
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
      path: packages/flutter_html_svg
  flutter_html_table: 
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
      path: packages/flutter_html_table
  flutter_html_video: 
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
      path: packages/flutter_html_video
  # flutter_html_audio:
  #   path: ../flutter_html_audio
  # flutter_html_iframe:
  #   path: ../flutter_html_iframe
  # flutter_html_math:
  #   path: ../flutter_html_math
  # flutter_html_svg:
  #   path: ../flutter_html_svg
  # flutter_html_table:
  #   path: ../flutter_html_table
  # flutter_html_video:
  #   path: ../flutter_html_video

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
