name: flutter_html_video
description: Video widget for flutter_html.
version: 3.0.0-alpha.4
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.22.2 <3.24.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html:
    git:
      url: https://github.com/NASunderland/flutter_html.git
      ref: 3.0.0-alpha.6
  # flutter_html:
  #   path: ../..

  video_player: '>=2.2.8 <3.0.0'
  chewie: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
